use_frameworks!

target 'WJQRCode_Example' do
  pod 'WJQRCode', :path => '../'

  target 'WJQRCode_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
